//Listar Usuarios
export const SAVE_DATA_FULLFIELLED = "SAVE_DATA_FULLFIELLED";
export const SAVE_DATA_LOADING = "SAVE_DATA_LOADING";
export const SAVE_DATA_REJECTED = "SAVE_DATA_REJECTED";

//Agregar usuarios
export const ADD_USER_FULLFILLED = "ADD_USER_FULLFILLED";
export const ADD_USER_LOADING = "ADD_USER_LOADING";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";