//Listar Usuarios
export const SAVE_DATA_FULLFIELLED = "SAVE_DATA_FULLFIELLED";
export const SAVE_DATA_LOADING = "SAVE_DATA_LOADING";
export const SAVE_DATA_REJECTED = "SAVE_DATA_REJECTED";

//Agregar usuarios
export const ADD_USER_FULLFILLED = "ADD_USER_FULLFILLED";
export const ADD_USER_LOADING = "ADD_USER_LOADING";
export const ADD_USER_REJECTED = "ADD_USER_REJECTED";

//Eliminar usuarios
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";

//Editar usuarios
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";